services:
  frontend:
    volumes:
        - ./frontend/nginx:/etc/nginx/conf.d
    build: 
      context: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - orchestrator
    networks:
      - backend-network

  orchestrator:
    build:
      context: .
      dockerfile: cmd/orchestrator_start/Dockerfile
    environment:
      - PORT=8080
      - TIME_ADDITION_MS=200
      - TIME_SUBTRACTION_MS=200
      - TIME_MULTIPLICATIONS_MS=300
      - TIME_DIVISIONS_MS=400
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/v1/expressions || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - backend-network

  agent:
    build:
      context: .
      dockerfile: cmd/agent_start/Dockerfile
    environment:
      - COMPUTING_POWER=4
      - ORCHESTRATOR_URL=http://orchestrator:8080  # Оставить как есть для внутренней связи
    depends_on:
      orchestrator:
        condition: service_healthy
    networks:
      - backend-network
networks:
  backend-network:
    driver: bridge